### ISSUE TITLE
Junior interface board PA0 to PB7 connection

### ISSUE THREAD

**Issue by robvb** [laurent-fr/junior_computer_replica#1]
Hello LaurantFR,

Can you confirm the Junior Interface card is working ..

BR rob

**Comment by laurent-fr** [comment]
Hi Rob,
I've not yet built the interface and I can't guarantee it's OK, I still have the components for this board ready to use but I did not took the time yet to order the pcb and test it (too many projects, too little time !)
Laurent

**Comment by robvb** [comment]
Bonjour Laurent,

First of all ,,  thank you for the beautiful work on the Junior Computer.
I ordered some of your interfaces pcb's (expected delivery,next week) and I could send you 2 pcs  (free of charge)  ;-)

BR rob

**Comment by laurent-fr** [comment]
Hi Rob,
thanks :-) Have you built the Junior card ? (this one should work !) 
I really hope there is no too much mistakes on the extension board (the GAL that replaces the PROM needs testing, and I remember I was not completely happy with the chip selects)
